#!/bin/bash
estado_programa=0

echo "Vamos a realizar la copia de seguridad del sistema"
cd /

carpetas=$(ls)
if [[ "copia_seguridad" in $carpetas ]]
then
    read -p "Cuentas con una carpeta llamada copia_seguridad. ¿Quieres reemplazarla? [y/n] " reemplazar_carpeta
    if [[ $reemplazar_carpeta = "y" ]]
    then
        sudo rm -r copia_seguridad
    elif [[ $reemplazar_carpeta = "n" ]]
    then
        echo "De acuerdo, no se hara nada con la carpeta"
        # HACER QUE SE MODIFIQUE EL NOMBRE DEL ARCHIVO
        estado_programa=1
    fi
fi

if [[ $estado_programa = 0 ]]
then
    cd /
    sudo mkdir copia_seguridad
    carpetas=$(ls)
    for carpeta in $carpetas
    do
        cd /home
        cp $carpeta /copia_seguridad
        cd copia_seguridad
        carpetas_comprobación=$(ls)
        if [[ $carpeta in $carpetas_compartidas ]]
        then
            echo "La carpeta "$carpeta" ha sido copiada correctamente"
        else
            echo "La carpeta "$carpeta" no ha podido copiarse en la copia de seguridad"
        fi
        sleep 3s
    done 
elif [[ $estado_programa = 1 ]]
then
    cd /
    sudo mkdir copia_seguridad_1
    carpetas=$(ls)
    for carpeta in $carpetas
    do
        cd /home
        cp $carpeta /copia_seguridad_1
        cd copia_seguridad
        carpetas_comprobación=$(ls)
        if [[ $carpeta in $carpetas_compartidas ]]
        then
            echo "La carpeta "$carpeta" ha sido copiada correctamente"
        else
            echo "La carpeta "$carpeta" no ha podido copiarse en la copia de seguridad"
        fi
        sleep 3s
    done 
fi
